services:

  db:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    env_file:
      - path: .env
        required: true
    restart: always
    networks:
      - internal
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./exported_db:/exported_db

  app:
    image: cosmtrek/air:v1.52.3
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    restart: always
    env_file:
      - path: .env
        required: true
    networks:
      - internal
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./main.go

  docs:
    image: cosmtrek/air:v1.52.3
    ports:
      - ${DOCS_PORT}:${DOCS_PORT}
    depends_on:
      - app
    env_file:
      - path: .env
        required: true
    networks:
      - internal
    volumes:
      - .:/app
    working_dir: /app/docs
    command: go run ./main.go

  adminer:
    image: adminer:4.8.1-standalone
    depends_on:
      - db
    restart: always
    ports:
      - 9999:8080
    networks:
      - internal

volumes:
  db_data:
#    name: url_shortener_db_data

networks:
  internal: